events {}
http {
  server {
    listen 3000;
    absolute_redirect off;
    location = / { return 302 /page-1; }
    location = /page-1 { proxy_pass http://127.0.0.1:4173/vue/page-1; }
    location = /page-2 { proxy_pass http://127.0.0.1:4173/vue/page-2; }
    location = /page-3 { proxy_pass http://127.0.0.1:4174/react/page-3; }
    location = /page-4 { proxy_pass http://127.0.0.1:4174/react/page-4; }
    location /vue/ { proxy_pass http://127.0.0.1:4173; }
    location /react/ { proxy_pass http://127.0.0.1:4174; }
  }
}
